version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  project_data:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
