default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: ProjectData_development

test:
  <<: *default
  database: ProjectData_test

production:
  <<: *default
  database: ${DATABASE}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  host: ${DB_HOST}
